### ISSUE TITLE
Last updated time incorrect

### ISSUE THREAD

**Issue by mbrigdan** [andyczerwonka/tyrion#134] opened 2015-07-29 05:01 UTC
We're seeing a site send new data and a new picture, but the time is stuck at "6 hours ago"
![image](https://cloud.githubusercontent.com/assets/11862839/8950273/9845eefe-357c-11e5-8228-018f4fee1dea.png)

**Comment by andyczerwonka** [comment] 2015-07-29 06:03
@mbrigdan how do you know reading are coming in?

**Comment by mbrigdan** [comment] 2015-07-29 15:32
We saw the numbers and picture update

**Comment by andyczerwonka** [comment] 2015-07-29 15:40
@mbrigdan please be more specific... are you saying that the value from the device changes but the date doesn't change? And is that for one site or for all sites?

**Comment by mbrigdan** [comment] 2015-08-03 19:52
That's exactly what we saw, the numbers on displayed changed, but the date didn't. We saw the same thing happen with the picture (picture changed, date didn't change). Its possible that the local time on the computer might have been wrong, and that caused the issue, I'm not sure (I haven't seen it happen again)

**Comment by andyczerwonka** [comment] 2015-08-03 20:01
The part that doesn't make sense is that it's only happening for a particular site, not all sites, so I don't think your hypothesis holds. 

The only thing I can think of is the pictures are coming in, so the PI is okay. The picture and readings are separate requests. The sensors are on the board and for some reason the site is not sending the data. Then again you're saying the numbers are changing so that doesn't make sense either.

I'd love to see this reproduced, but I'm closing for now given you can't reproduce it.

**Closed by andyczerwonka** 2015-08-03 20:01 UTC
Labels: question
